# @package _global_

defaults:
  - /params/bigger_model.yaml
  - override /domain: cNATL
  - _self_

trainer:
  accumulate_grad_batches: 2

datamodule:
  input_da:
    _target_: src.utils.load_full_natl_data
    obs_var: five_nadirs
  dl_kw: {batch_size: 8}
  aug_factor: 0
  aug_only: False
