channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - pip
  - pytorch=1.13
  - pytorch-cuda=11.6
  - pyinterp
  - xarray
  - dask
  - netCDF4
  - bottleneck
  - pip:
    - pytorch-lightning==1.8.*
    - GitPython
    - einops
    - hydra-core
    - kornia
