trainer:
  _target_: pytorch_lightning.Trainer
  _partial_: true
  gpus: [4]
  logger: {_target_: pytorch_lightning.loggers.CSVLogger, save_dir: logs}
  max_epochs: 300
  callbacks:
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      monitor: val_rmse
      save_last: True
      verbose: True
    - _target_: pytorch_lightning.callbacks.ModelSummary
      max_depth: 2
    - _target_: pytorch_lightning.callbacks.GradientAccumulationScheduler
      scheduling: {20: 2, 50: 4}


datamodule:
  _target_: src.data.BaseDataModule
  _partial_: true
  input_da: 
    _target_: src.data.load_altimetry_data
    path: /raid/localscratch/qfebvre/sla-data-registry/qdata/natl20.nc
    coarsen: {lat: 2, lon: 2}
  domains:
    train: 
      time: {_target_: builtins.slice, _args_: ['2013-02-04', '2013-09-30']}
    val: 
      time: {_target_: builtins.slice, _args_: ['2012-12-15', '2013-02-24']}
    test: 
      time: {_target_: builtins.slice,  _args_: ['2012-10-01', '2012-12-20']}
  xrds_kw:
    patch_dims: 
      time: 29
      lat: ${div:240,${oc.select:datamodule.input_da.coarsen.lat,1}}
      lon: ${div:240,${oc.select:datamodule.input_da.coarsen.lon,1}}
    strides: 
      time: 1
      lat: ${div:240,${oc.select:datamodule.input_da.coarsen.lat,1}}
      lon: ${div:240,${oc.select:datamodule.input_da.coarsen.lon,1}}
  dl_kw: {batch_size: 4, num_workers: 1}
  aug_factor: 2



model:
  _target_: src.models.Lit4dVarNet
  _partial_: true
  rec_weight:
      _target_: src.utils.get_constant_crop
      patch_dims: ${datamodule.xrds_kw.patch_dims}
      crop: 
        time: 8
        lat: ${div:20,${oc.select:datamodule.input_da.coarsen.lat,1}}
        lon: ${div:20,${oc.select:datamodule.input_da.coarsen.lon,1}}
  solver: 
    _target_: src.models.GradSolver
    n_step: 15
    cut_graph_freq: 5
    prior_cost: 
      _target_: src.models.BilinAEPriorCost
      dim_in: ${datamodule.xrds_kw.patch_dims.time}
      dim_hidden: 64
    obs_cost: 
      _target_: src.models.BaseObsCost
    grad_mod: 
      _target_: src.models.ConvLstmGradModel
      dim_in: ${datamodule.xrds_kw.patch_dims.time}
      dim_hidden: 128


entrypoints:
  - _target_: pytorch_lightning.Trainer.fit
    self: ${singleton:trainer}
    model: ${singleton:model}
    datamodule: ${singleton:datamodule}
  - _target_: pytorch_lightning.Trainer.test
    self: ${singleton:trainer}
    model: ${singleton:model}
    datamodule: ${singleton:datamodule}
    ckpt_path: 'best'
  - _target_: src.utils.diagnostics
    model: ${singleton:model}
    datamodule: ${singleton:datamodule}
      
