# @package _global_

paths:
    GT: /DATASET/turbidity_new/bbp/GT_2010to2021_log10.nc
    patch: /DATASET/turbidity_new/bbp/Obs_patch_2010to2021_log10.nc

trainer:
  _target_: pytorch_lightning.Trainer
  inference_mode: False
  gradient_clip_val: 0.5
  accelerator: gpu
  devices: 1
  logger: 
    _target_: pytorch_lightning.loggers.CSVLogger
    save_dir: ${hydra:runtime.output_dir}
    name: ${hydra:runtime.choices.xp}
    version: ''
  max_epochs: 100
  callbacks:
    - _target_: src.versioning_cb.VersioningCallback
    - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      monitor: val_mse
      save_top_k: 3
      filename: '{val_mse:.4f}-{epoch:03d}'

datamodule:
  _target_: src.data.BaseDataModule
  input_da: 
    _target_: src.utils.load_turbidity_data
    path1: ${paths.GT}
    path2: ${paths.patch}
    var: "BBP443"
  domains:
    train:
      time: {_target_: builtins.slice, _args_: ['2018-01-01', '2019-12-31']}
    val: 
      time: {_target_: builtins.slice, _args_: ['2019-01-01', '2019-12-31']}
    test: 
      time: {_target_: builtins.slice, _args_: ['2020-01-01', '2021-12-31']}
    #~ test: 
      #~ time: 
        #~ _target_: builtins.slice, _args_: ${adjust_testslices:['2020-01-01', '2021-12-31']}
  xrds_kw:
    patch_dims: { time: 7, lat: 240, lon: 240}
    strides: { time: 1, lat: 240, lon: 240}
  dl_kw: {batch_size: 8, num_workers: 10}
  aug_factor: 0
  aug_only: True

model:
  _target_: src.models.Lit4dVarNet
  opt_fn:
    _target_: src.utils.cosanneal_lr_adam
    _partial_: true
    lr: 1e-3
    T_max: 175
  rec_weight:
      _target_: src.utils.get_triang_time_wei
      patch_dims: ${datamodule.xrds_kw.patch_dims}
      crop: {time: 0, lat: 0, lon: 0}
      offset: 1
  solver: 
    _target_: src.models.GradSolver
    post_proj: false
    n_step: 10
    lr_grad: 0.2
    prior_cost: 
      _target_: src.models.BilinAEPriorCost
      dim_in: ${datamodule.xrds_kw.patch_dims.time}
      dim_hidden: 100
    obs_cost: 
      _target_: src.models.BaseObsCost
    grad_mod: 
      _target_: src.models.ConvLstmGradModel
      dim_in: ${datamodule.xrds_kw.patch_dims.time}
      dim_hidden: 150


entrypoints:
  - _target_: pytorch_lightning.seed_everything
    seed: 333
  - _target_: src.train.base_training
    trainer: ${trainer}
    lit_mod: ${model}
    dm: ${datamodule}
#    test_fn:
#      _target_: src.utils.diagnostics
#      _partial_: true
#      test_domain:
#        time: {_target_: builtins.slice, _args_: ["2021-02-09", "2021-06-30"]}
